FROM jgoldfar/pdf2htmlex-deps

ENV PDF2HTMLEX_SOURCE "https://github.com/jgoldfar/pdf2htmlEX.git"

COPY CMakeLists.txt.patch ${WORKDIR}/

COPY dobuild.sh ${WORKDIR}/

# Install pdf2htmlEX
RUN cd ${WORKDIR} && \
    git clone --depth 1 ${PDF2HTMLEX_SOURCE} && \
    cd pdf2htmlEX && ${WORKDIR}/dobuild.sh && rm ${WORKDIR}/dobuild.sh

VOLUME /data/
