FROM jgoldfar/pdf2htmlex-deps

# Install pdf2htmlEX
COPY pdf2htmlEX ${WORKDIR}/pdf2htmlEX

COPY CMakeLists.txt.patch ${WORKDIR}/

COPY dobuild.sh ${WORKDIR}/

RUN cd ${WORKDIR}/pdf2htmlEX && ${WORKDIR}/dobuild.sh && rm ${WORKDIR}/dobuild.sh

VOLUME /data/
